#!/usr/bin/env python3
"""Attendance gate: is every participation backed by a source produced at or after
the event that names the student?

Inputs (all generated by the existing pipeline):
  <ol>/data/corroboration.json   per-edition sources, each with a `timing` tag
                                 (post | event | pre | ref | unknown); a year may
                                 also carry `"attested": {"<person-id>": "<reason>"}`
                                 — curated post-event evidence that is not a
                                 fetchable URL (a private communication, a document
                                 that exists only off the web). Post-event evidence
                                 that IS a URL but cannot be read (a social post, a
                                 diploma image) belongs on the source entry instead,
                                 as `"names": ["<person-id>", ...]`, which
                                 check_source_names.py records at level `attested`.
  site/data/source_names.json    which roster members each source's text names
  site/data/people.json          the participations to check

A participation is
  confirmed   named by at least one `post` or `event` source of that edition, or
              listed in that year's `attested` map;
  pre-only    named only by `pre` / `ref` / `unknown` sources (selected, but no
              evidence that the student actually competed);
  unnamed     no fetched source of that edition names the student at all.

Scope: the gate only sees what the site publishes. A raw record flagged
`"attendance": "unconfirmed"` is skipped by build_people.py, so it is not in
people.json and never appears here — that flag is the way to hold a row back
(keep it in the dataset, out of the site) when a pre-only participation should
not be shown at all, rather than merely reported as pre-only.

Usage: python3 site/scripts/check_attendance.py [--strict] [--only ol1,ol2]
  --strict   exit 1 when any pre-only participation exists (for CI-style gating)
Writes a Markdown report to tmp/attendance_report.md and prints the summary.
"""
import argparse
import json
import sys
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path

SITE = Path(__file__).resolve().parent.parent
ROOT = SITE.parent
sys.path.insert(0, str(SITE / "scripts"))
from build_people import DATASETS  # noqa: E402

OK_TIMING = {"post", "event"}


def load(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def host(u):
    return u.split("/")[2] if "//" in u else u


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--strict", action="store_true")
    ap.add_argument("--only", help="comma-separated dataset ids")
    args = ap.parse_args()
    datasets = args.only.split(",") if args.only else list(DATASETS)

    people = load(SITE / "data" / "people.json")["people"]
    names = load(SITE / "data" / "source_names.json")["byOlympiad"]
    timing = {}      # (ol, year, url) -> timing
    attested = {}    # (ol, year) -> {personId: reason}
    untagged = Counter()
    for ds in datasets:
        corr = load(ROOT / ds / "data" / "corroboration.json")
        for y in corr["years"]:
            if y.get("attested"):
                attested[(ds, y["year"])] = y["attested"]
            for s in y["sources"]:
                t = s.get("timing")
                if t is None:
                    untagged[ds] += 1
                    t = "untagged"
                timing[(ds, y["year"], s["url"])] = t

    rows = []  # (status, ds, year, pid, name, detail)
    for p in people:
        for x in p["participations"]:
            ds, year = x["olympiad"], x["year"]
            if ds not in datasets:
                continue
            by_url = names.get(ds, {}).get(str(year), {})
            naming = [(u, timing.get((ds, year, u), "untagged"), (r.get("found") or {})[p["id"]])
                      for u, r in by_url.items() if p["id"] in (r.get("found") or {})]
            reason = attested.get((ds, year), {}).get(p["id"])
            if reason:  # post-event evidence with no URL of its own: counts as a post source
                naming.append((f"attested: {reason}", "post", "attested"))
            post = [(u, lv) for u, _t, lv in naming if _t in OK_TIMING]
            if post:
                # detail is filled only when the confirmation rests on curation alone
                curated = [u if u.startswith("attested: ") else f"attested on {host(u)}"
                           for u, lv in post if lv == "attested"]
                rows.append(("confirmed", ds, year, p["id"], p["name"],
                             "; ".join(curated) if len(curated) == len(post) else ""))
            elif naming:
                hosts = sorted({host(u) + f" [{t}]" for u, t, _lv in naming})
                rows.append(("pre-only", ds, year, p["id"], p["name"], ", ".join(hosts)))
            else:
                rows.append(("unnamed", ds, year, p["id"], p["name"], ""))

    per = defaultdict(Counter)
    for st, ds, *_ in rows:
        per[ds][st] += 1
    tot = Counter(st for st, *_ in rows)

    lines = [f"# Attendance check", "",
             f"Generated {datetime.now(timezone.utc).isoformat(timespec='seconds')} by `site/scripts/check_attendance.py`.", "",
             "| dataset | participations | confirmed | pre-only | unnamed | untagged sources |", "|---|---:|---:|---:|---:|---:|"]
    for ds in datasets:
        c = per[ds]
        n = sum(c.values())
        lines.append(f"| {ds} | {n} | {c['confirmed']} | {c['pre-only']} | {c['unnamed']} | {untagged[ds]} |")
    lines.append(f"| **total** | {sum(tot.values())} | {tot['confirmed']} | {tot['pre-only']} | {tot['unnamed']} | {sum(untagged.values())} |")
    lines += ["", f"## Pre-only participations ({tot['pre-only']})", ""]
    for st, ds, year, pid, name, detail in sorted(rows, key=lambda r: (r[1], r[2], r[4])):
        if st == "pre-only":
            lines.append(f"- {ds} {year} — {name} (`{pid}`) — named only by: {detail}")
    lines += ["", f"## Unnamed participations ({tot['unnamed']})", ""]
    for st, ds, year, pid, name, detail in sorted(rows, key=lambda r: (r[1], r[2], r[4])):
        if st == "unnamed":
            lines.append(f"- {ds} {year} — {name} (`{pid}`)")
    # confirmations that rest on curation alone: an unreadable post-event source
    # attested with "names", or a year's "attested" map — auditable in one place
    curated = [r for r in sorted(rows, key=lambda r: (r[1], r[2], r[4])) if r[0] == "confirmed" and r[5]]
    lines += ["", f"## Confirmed by curated attestation ({len(curated)})", ""]
    for st, ds, year, pid, name, detail in curated:
        lines.append(f"- {ds} {year} — {name} (`{pid}`) — {detail}")
    out = ROOT / "tmp" / "attendance_report.md"
    out.parent.mkdir(exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"attendance: {sum(tot.values())} participations — confirmed {tot['confirmed']} ({len(curated)} by curated "
          f"attestation), pre-only {tot['pre-only']}, unnamed {tot['unnamed']}; "
          f"untagged sources {sum(untagged.values())} -> {out}")
    if args.strict and tot["pre-only"]:
        sys.exit(1)


if __name__ == "__main__":
    main()
